### ISSUE TITLE
Docker image doesn't seem to match what's published here?

### ISSUE THREAD

**Issue by Zebble** [aneisch/thermostat_api_server_docker#1]
Hi @aneisch !

Thanks so much for this API server.  I had been hacking around with this thermostat and ICP's cloud service for a while and was going to publish something that connected to the cloud service.  I like this method a lot better as it now keeps things local.  The only reason I would normally prefer to keep things connected to the cloud was for firmware updates but since ICP doesn't support firmware updates over their cloud and the only way to get firmwares updates is through an HVAC dealer, this API server is absolutely perfect.

I did try to roll this out with your example docker-compose but the image that gets pulled doesn't seem to match what you have published here.  It runs some sort of shell script that connects using the mosquitto client?  I ended up just creating my own Dockerfile and building locally and that works perfectly.

I added mqtt name and password as well.  I'll do a pull request at some point.

**Comment by aneisch** [comment]
Sorry about that I had the wrong image in the readme! It's fixed now! So happy you like it, please submit any PRs as you see fit, and thanks in advance for the contributions!
