### ISSUE TITLE
Sending to thermostat

### ISSUE THREAD

**Issue by ullms1** [aneisch/thermostat_api_server_docker#3]
Able to get the api to communicate with the MQTT server, thermostat sending information, but unable to control the thermostat via the MQTT server (homeassistant).  Any suggestions?

**Comment by aneisch** [comment]
If you `docker logs -f CONTAINER_NAME` do you see log entries for commands from HA?

**Comment by ullms1** [comment]
Here is a portion of the log file

i_server  | Connecting to MQTT
thermostat_api_server  | Connected to MQTT
thermostat_api_server  | Subscribed to homeassistant/climate/living/cmnd/#
thermostat_api_server  | Published Config Entries
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:54:52] "POST
/systems/2617N192113 HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:54:54] "POST
/systems/2617N192113/notifications HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:54:56] "POST
/systems/2617N192113/status HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:54:58] "POST
/systems/2617N192113/odu_status HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:55:02] "POST
/systems/2617N192113/idu_faults HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 19:55:04] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:55:06] "POST
/systems/2617N192113/odu_faults HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 19:56:04] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/temperature 70.0
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 19:57:04] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode heat
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 19:58:04] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 192.168.0.102 - - [12/Nov/2023 19:58:15] "POST
/systems/2617N192113/history HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 19:59:04] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode off
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:00:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:01:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:02:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:03:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:04:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:05:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | 127.0.0.1 - - [12/Nov/2023 20:06:05] "GET /time
HTTP/1.1" 200 -
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode cool
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode heat
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode heat
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode heat
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/operating_mode heat
thermostat_api_server  | New message:
homeassistant/climate/living/cmnd/temperature 64.0

**Comment by aneisch** [comment]
It looks like the most recent contact from the thermostat is `12/Nov/2023 19:56:04` but your command is sent from HA right after that. 

I see the same where sometimes the thermostat simply stops communicating with the API server. It usually doesn't last too long but I haven't figured out if this is a code problem or just an oddity with the thermostat itself.

**Comment by ullms1** [comment]
I'm thinking it's an issue with the thermostat firmware.  It doesn't stay
connected with the observer API website either.  If the power is
disconnected it will connect when power is restored but then disconnects
after an hour or so, and never reconnects.

I tried your API to see if it was just observers web API.  Great work
though.

Thanks for the help.

**Comment by aneisch** [comment]
Mine has been _pretty_ stable. I think it's really susceptible to wifi dropouts and such. I have noticed that if I manually kill the tcp connection between my API server and the thermostat that will get it to "reset" and start working again.
